Repository GSG-G11/Task-manager-A, pull requests merged in 2022-03, with the labels that each got.

#3 done with initial file structure
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/components/AddTaskForm.jsx
  src/index.css
  src/index.js
Labels: Done

#7 done with add task component
  src/App.js
  src/components/AddTaskForm.jsx
Labels: Done

#8 cerate-react-card
  package-lock.json
  src/App.css
  src/components/TaskCard.jsx
Labels: Done

#12 add icons to task cards
  package-lock.json
  package.json
  src/components/TaskCard.jsx
Labels: Awaiting Review, Done

#13 create tesk list component
  src/App.css
  src/App.js
  src/components/TaskList.jsx
Labels: Done

#22 Fix check issue , add nav bar button #20
  public/index.html
  src/App.css
  src/App.js
  src/components/TaskCard.jsx
  src/components/nav/Navbar.jsx
  src/components/nav/nav.css
Labels: Awaiting Review

#24 fix rendering the edit form
  .gitignore
  src/App.js
  src/components/EditTask.jsx
  src/components/TaskCard.jsx
Labels: Awaiting Review
